name: Continuous Delivery
on:
  # Runs when there is a push to the specified branches. If the commit only affects files in 'paths-ignore', the workflow will not run.
  push:
    tags:
        - "v*"

  
  # Allows manual execution of the workflow from the GitHub UI
  workflow_dispatch:
jobs:
  continuous-delivery:
    uses: ./.github/workflows/container-app-delivery.yml
    secrets: inherit
    with:
      environment: development
