name: Continuous Deployment - Container Apps

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        type: environment
      image-tag:
        description: 'Immutable image tag to deploy, e.g. sha-7685b57 or v1.2.3'
        required: true
        type: string


jobs:
  continuous-deployment:
    uses: ./.github/workflows/continuous-deployment-container-apps.yml
    with:
      environment: ${{ inputs.environment }}
      image-tag: ${{ inputs.image-tag }}
    secrets: inherit
